#define RL_BINOP_ADD 0
#define RL_BINOP_SUB 1
#define RL_BINOP_MUL 2
#define RL_BINOP_DIV 3
#define RL_BINOP_EQU 4
#define RL_BINOP_NEQ 5
#define RL_BINOP_SHL 6
#define RL_BINOP_SHR 7
#define RL_BINOP_AND 8
#define RL_BINOP_OR  9
#define RL_BINOP_XOR 10
#define RL_BINOP_L_AND 11
#define RL_BINOP_L_OR  12
#define RL_BINOP_GTH 13
#define RL_BINOP_LTH 14
#define RL_BINOP_LEQ 15
#define RL_BINOP_GEQ 16
#define RL_BINOP_SADD 17
#define RL_BINOP_SSUB 18
#define RL_BINOP_SMUL 19
#define RL_BINOP_SDIV 20
#define RL_BINOP_SEQU 21
#define RL_BINOP_SNEQ 22
#define RL_BINOP_SGTH 23
#define RL_BINOP_SLTH 24
#define RL_BINOP_SLEQ 25
#define RL_BINOP_SGEQ 26

#define RL_UNYOP_PEQ 0
#define RL_UNYOP_SEQ 1
#define RL_UNYOP_MEQ 2
#define RL_UNYOP_DEQ 3
#define RL_UNYOP_L_NOT 4
#define RL_UNYOP_NOT 5
#define RL_UNYOP_AEQ 6
#define RL_UNYOP_OEQ 7
#define RL_UNYOP_XEQ 8
